# Generated by Django 5.2.3 on 2025-06-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMMS_Lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('biomedico', 'Biomedico')], max_length=20),
        ),
    ]
